name = "May the Odds"
author = "kodiitulip"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cac477249095c7719d26a7f526ef34db8f6f8c87dd7597a040b537f49d27fdb2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
datapack-folder = "datapacks"
